# sample compsoe file for running 2 app instances, 1 DB instance and nginx as load balancer.

# assumption:
# the mounted nginx config file has upstream backend specified, pointing to "app" server

# to run the setup:
# docker-compose -f docker-compose-app.yml up --scale app=2

version: '3.7'
services:
 app:
  build:
   context: ./app
   dockerfile: ./app_dir/Dockerfile
   target: debug
  image: app/app_debug:master
  env_file: .env
  entrypoint: "/opt/app/entrypoint.sh"
  ports:
   - "80"
  depends_on:
   - db
   
 db:
  image: percona:8.0
  environment:
   - MYSQL_ROOT_PASSWORD: "password"
  ports:
   - "3306:3306"
   
 nginx:
  image: nginx:latest
  ports:
   - "8080:80"
  volumes:
   - ./app_dir/nginx.conf:/etc/nginx/nginx.conf:ro
   - ./app/static/html:/usr/share/nginx/html:ro
  environment:
   - NGINX_HOST=app.com
   - NGINX_PORT=80
  depends_on:
   - db
   - app







